### ISSUE TITLE
Search return format is different when results are empty

### ISSUE THREAD

**Issue by wandell** [flywheel-io/sdk#51]
Thanks for moving this project along.  I have started working on the Matlab side; also @lmperry and I plan to devote time to the organization of the repository on Wednesday after the CNI site is up. We need to have the Matlab SDK reasonably functional to make CNI users interested in engaging.

I think the plan we all have is that the scitranClient version of Flywheel.m will be exactly the one you deliver. When something turns up that we need a change, we will send you a message.  Here is the first one.

When Flywheel.search returns an empty result, the return variable has not 'results' slot.  

            % Result may be empty
            result = Flywheel.handleJson(status,cmdout);
            
            % In my local version, I added this to fix the null result case. 
            %  But you might force the return to always have a results slot, even if empty
            % Then we would note need this line. 
            if ~isfield(result,'results'), result.results = []; end

**Comment by jenreiter** [comment]
@kofalt I believe there is a change within search that slightly changes how results are returned... will this fix this issue in Matlab's search? Or will we still need to better handle the null return?

**Comment by kofalt** [comment]
Yes, Brian & Michael I think this change can make things a bit easier: the API has added a simple mode that will apply [this transform](https://github.com/scitran/core/blob/4958909fcd4ab275ed938858cff4329064575246/api/handlers/dataexplorerhandler.py#L578-L580) to the results, returning only the `_source` key for each search result. Because it is using an array construction instead of the [map construction below](https://github.com/scitran/core/blob/4958909fcd4ab275ed938858cff4329064575246/api/handlers/dataexplorerhandler.py#L583-L586), I think you'll instead be able to use the `result` variable from your code above without having to go to `results.results`.

Jen and I were planning to make this new mode the default `Search`, and move the old format to `SearchRaw` in case anyone needs the old layout. I want to make that switch at the same time we add any search helper functions, to limit the frequency of breaking changes.

Jen - let's chat tomorrow about what we need to do there. Then I can make a SDK branch with the new format.

**Comment by kofalt** [comment]
Excellent. It sounds like it won't be hard for you guys to port your stuff over, which was my main concern. Odds are good that we'll have a branch later today with this change; once it works for your script we can merge it!

I will leave SearchRaw in for at least one release, as an easy fallback for everyone else, and revisit removal at a later date. Megan is confident that consumers will not need that format & facets.

**Comment by wandell** [comment]
Thanks.  We are on it.  And your speed is appreciated.


My goal is to have customer-facing demonstrations of the Matlab-SDK for meeting over the next few weeks.


Brian

________________________________

**Comment by kofalt** [comment]
Closed in #53
